import type { Job, Interview } from "./types"

// Mock data for preview
export const mockJobs: Job[] = [
  {
    id: 1,
    company: "Google",
    position: "Software Engineer",
    jobUrl: "https://careers.google.com/jobs/123",
    applicationDate: new Date("2024-01-15"),
    status: "interview",
    notes: "大公司，技术栈匹配",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: 2,
    company: "Microsoft",
    position: "Frontend Developer",
    jobUrl: "https://careers.microsoft.com/jobs/456",
    applicationDate: new Date("2024-01-20"),
    status: "applied",
    notes: "微软的前端职位，React技术栈",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: 3,
    company: "Apple",
    position: "iOS Developer",
    jobUrl: "https://jobs.apple.com/jobs/789",
    applicationDate: new Date("2024-01-25"),
    status: "rejected",
    notes: "要求Swift经验较多",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: 4,
    company: "Meta",
    position: "Full Stack Engineer",
    jobUrl: "https://www.metacareers.com/jobs/101112",
    applicationDate: new Date("2024-02-01"),
    status: "offer",
    notes: "收到offer，待考虑",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: 5,
    company: "Amazon",
    position: "Cloud Engineer",
    jobUrl: "https://amazon.jobs/jobs/131415",
    applicationDate: new Date("2024-02-05"),
    status: "applied",
    notes: "AWS相关职位",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
]

export const mockInterviews: Interview[] = [
  {
    id: 1,
    jobId: 1,
    round: 1,
    type: "technical",
    scheduledDate: new Date("2024-01-22T14:00:00"),
    interviewer: "张工程师",
    result: "passed",
    feedback: "技术面试表现良好，算法题解答正确",
    notes: "准备了常见算法题",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: 2,
    jobId: 1,
    round: 2,
    type: "hr",
    scheduledDate: new Date("2024-01-25T10:00:00"),
    interviewer: "HR李女士",
    result: "pending",
    feedback: "",
    notes: "等待HR面试结果",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: 3,
    jobId: 4,
    round: 1,
    type: "phone",
    scheduledDate: new Date("2024-02-08T15:30:00"),
    interviewer: "王经理",
    result: "passed",
    feedback: "电话面试顺利，对项目经验很感兴趣",
    notes: "重点介绍了React项目经验",
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-08"),
  },
  {
    id: 4,
    jobId: 4,
    round: 2,
    type: "onsite",
    scheduledDate: new Date("2024-02-12T09:00:00"),
    interviewer: "技术团队",
    result: "passed",
    feedback: "现场面试通过，团队氛围很好",
    notes: "现场编程题完成得不错",
    createdAt: new Date("2024-02-12"),
    updatedAt: new Date("2024-02-12"),
  },
]
